### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by VidJa** [jasperlinthorst/reveal#19]
after a succesful installation
reveal align tests/1a.fa tests/1b.fa
fails on step 2
reveal rem  tests/1a.fa tests/1b.gfa -m20  -o prg.gfa
03/15/2018 12:03:03 PM Reading fasta: tests/1a.fa ...
03/15/2018 12:03:03 PM Reading graph: tests/1b.gfa ...
03/15/2018 12:03:03 PM No paths defined in GFA, exit.

**Comment by jasperlinthorst** [comment]
Sorry about that... it should be fixed now.
Thanks for letting me know!

Jasper

**Comment by ThijsMaas** [comment]
Still the same test fail..

`reveal align tests/1a.fa tests/1b.fa | sh`
03/16/2018 03:44:52 PM Auto determined minchainsum to 663
03/16/2018 03:44:52 PM Assembly consists of 1 contigs.
03/16/2018 03:44:52 PM Using chains to layout the assembly.
03/16/2018 03:44:52 PM Found 1 chains for contig: An19_A_niger_CBS_513_88_0
03/16/2018 03:44:52 PM The following parts of contigs could not be placed anywhere on the reference sequence.
03/16/2018 03:44:52 PM 100.00% (96465 out of 96465) of the assembly was placed with respect to the reference.
03/16/2018 03:44:53 PM Loading input...
03/16/2018 03:44:53 PM Reading fasta: tests/1a.fa ...
03/16/2018 03:44:53 PM Reading graph: tests/1b.gfa ...
03/16/2018 03:44:53 PM No paths defined in GFA, exit.

**Comment by jasperlinthorst** [comment]
Just to be sure... Did you do a new git 'pull' or 'clone'? I just did and things seem to work for me.

**Comment by ThijsMaas** [comment]
I removed the installed files and the cloned repository, cloned a new one and installed. Do I need to do something differently?

**Comment by VidJa** [comment]
Might it be a documentation issue?
reveal align tests/1a.fa tests/1**b**.fa | sh fails
reveal align tests/1a.fa tests/1**f.**fa | sh passes

**Comment by ThijsMaas** [comment]
That works for me as well.

**Comment by jasperlinthorst** [comment]
No, this shouldn't be a documentation issue... both should work.

Can you run:

"reveal transform tests/1a.fa tests/1b.fa -o test.gfa"

Then use grep to see if there's a path line in test.gfa:

"grep "^P" test.gfa"

There should be, if not, the 'reveal' command is still pointing to the old version and there's a problem with the setup script...

Let me know.

**Comment by ThijsMaas** [comment]
There is no path line in test.gfa, only a header (H) and 1 big segment (S)

**Comment by jasperlinthorst** [comment]
I'd suggest a clean installation on a different environment, as this has to be a version problem, which I can not reproduce. This problem was most likely due to a bug which is fixed in the current master branch. If for some reason the installation fails to update the old version of reveal that is installed on your system, then its very hard for me to help without knowing the specifics of your environment... If you really can't figure out where things go wrong with the installation, write me an email with the specifics of your environment and I'll see if I can assist with that: jasper.linthorst@gmail.com

**Comment by ThijsMaas** [comment]
Tried it again on a different environment and it's working now, thanks.
